defaults:
  - benchmark: continual
  - algorithm: random_policy
  - env: continualbench
  - logging: default
  - _self_

seed: 0

train:
  episodes_per_task: 100

eval:
  eval_video_steps: 10000
  num_eval_episodes: 10
