domain: sequential
benchmark_mode: continual
task_list:
  - block
  - button
  - door
  - peg
  - window
  - faucet

shuffle_tasks: false
seed: 0
num_envs: 10
vec_env_cls: SubprocVecEnv
single_task_name: null

logging:
  project: continual-bench
  enable_wandb: true
  wandb_entity: jivani-aahil-university-of-ottawa

train:
  episodes_per_task: 100

eval:
  eval_video_steps: 10000
  num_eval_episodes: 10